/* This file is generated by scripts automatively.
 * do not change it by hand.
 */

#include "../../include/GNeuron.h"
#include "../../include/GSynapse.h"
#include "../utils/TypeFunc.h"

void* (*createType[])() = { createConstant, createPoisson, createArray, createDecide, createFFT, createMem, createMax, createLIFE, createTJ, createStatic, createLIFEB};

size_t (*getTypeSize[])() = { getConstantSize, getPoissonSize, getArraySize, getDecideSize, getFFTSize, getMemSize, getMaxSize, getLIFESize, getTJSize, getStaticSize, getLIFEBSize};

int (*allocType[])(void *, int) = { allocConstant, allocPoisson, allocArray, allocDecide, allocFFT, allocMem, allocMax, allocLIFE, allocTJ, allocStatic, allocLIFEB};

int (*freeType[])(void *) = { freeConstant, freePoisson, freeArray, freeDecide, freeFFT, freeMem, freeMax, freeLIFE, freeTJ, freeStatic, freeLIFEB};

int (*addTypeConnection[])(void *, int *) = { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, addStaticConnection, NULL};

void (*mpiSendType[])(void *data, int rank, int offset, int size) = { mpiSendConstant, mpiSendPoisson, mpiSendArray, mpiSendDecide, mpiSendFFT, mpiSendMem, mpiSendMax, mpiSendLIFE, mpiSendTJ, mpiSendStatic, mpiSendLIFEB};

void (*mpiRecvType[])(void **data, int rank, int size) = { mpiRecvConstant, mpiRecvPoisson, mpiRecvArray, mpiRecvDecide, mpiRecvFFT, mpiRecvMem, mpiRecvMax, mpiRecvLIFE, mpiRecvTJ, mpiRecvStatic, mpiRecvLIFEB};

